apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lognest.fullname" . }}-ui
  namespace: {{ include "lognest.namespace" . }}
  labels:
    {{- include "lognest.labels" . | nindent 4 }}
data:
  app.py: |
{{ .Files.Get "files/app.py" | indent 4 }}
  requirements.txt: |
    flask==3.0.3
    gunicorn==22.0.0
