apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lognest.fullname" . }}-collector-script
  namespace: {{ include "lognest.namespace" . }}
  labels:
    {{- include "lognest.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-9"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  collect.py: |
{{ .Files.Get "files/collect.py" | indent 4 }}
  index_db.py: |
{{ .Files.Get "files/index_db.py" | indent 4 }}
