apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.storage.pv.name }}
  labels:
    {{- include "lognest.labels" . | nindent 4 }}
    lognest/pv: "true"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-11"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  capacity:
    storage: {{ .Values.storage.pvc.size }}
  accessModes:
    - {{ .Values.storage.pvc.accessMode }}
  # Retain means the NFS directory and data survive PVC deletion
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storage.storageClassName }}
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: {{ .Values.storage.nfsServer }}
    # This is the exact folder name on the NFS server — fixed, predictable
    path: {{ .Values.storage.nfsPath }}/{{ .Values.storage.pv.subPath }}
  # Bind only to our specific PVC
  claimRef:
    name: {{ .Values.storage.pvc.name }}
    namespace: {{ include "lognest.namespace" . }}
